---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-configmap
  namespace: flux-system
data:
  values.yaml: |
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      tag: v0.4.2
