---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-configuration
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: cluster-configuration
  path: ./cluster
  prune: true
  validation: client
  postBuild:
    substitute:
      component_path: component
